openapi: 3.0.1
info:
  title: envrio api
  version: 1.1.0
servers:
  - url: https://envrio.org/api
tags:
  - name: Authentication
  - name: Monitoring Equipment Info
  - name: Data Retrieving
paths:
  /auth:
    post:
      tags:
        - Authentication
      summary: User Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Invalid or missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '501':
          description: Operation not supported by this service implementation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
  /stations:
    get:
      security:
        - bearerAuth: []
      tags:
        - Monitoring Equipment Info
      summary: Get Stations Info
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationsResponse'
        '401':
          description: Invalid or missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '501':
          description: Operation not supported by this service implementation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
  /station_sensors:
    get:
      security:
        - bearerAuth: []
      tags:
        - Monitoring Equipment Info
      summary: Get Sensors Info
      parameters:
        - description: the sensor uniq identifier number
          name: station_id
          required: true
          in: query
          schema:
            $ref: '#/components/schemas/station_id'
          example: '123'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationSensorsResponse'
              example:
                - sensor_id: 123
                  measurement: air_temperature
                  unit: ''
                - sensor_id: 124
                  measurement: relative_humidity
                  unit: '%'
        '400':
          description: Invalid or missing parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '401':
          description: Invalid or missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '404':
          description: The advice was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
  /station_data:
    get:
      security:
        - bearerAuth: []
      tags:
        - Data Retrieving
      summary: Retrieve station sensor and meters time series
      parameters:
        - description: the station uniq identifier number
          name: station_id
          required: true
          in: query
          schema:
            $ref: '#/components/schemas/station_id'
          example: '1'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationDataResponse'
              example:
                station_id: 1
                station_data:
                  air_temperature:
                    data:
                      timestamp:
                        - 1700168549
                        - 1700254926
                        - 1700341284
                      value:
                        - 22
                        - 23.5
                        - 24
                  relative_humidity:
                      timestamp:
                        - 1700168549
                        - 1700254926
                        - 1700341284
                      value:
                        - 70
                        - 70.2
                        - 70.1
        '401':
          description: Invalid or missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '404':
          description: The advice was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
  /sensor_data:
    get:
      security:
        - bearerAuth: []
      tags:
        - Data Retrieving
      summary: Retrieve sensor time series
      parameters:
        - description: the sensor uniq identifier number
          name: sensor_id
          required: true
          in: query
          schema:
            $ref: '#/components/schemas/sensor_id'
          example: '123'
        - description: Timeseries start point
          name: start
          required: false
          in: query
          schema:
            $ref: '#/components/schemas/start'
          example: 1700168549
        - description: Timeseries end point
          name: end
          required: false
          in: query
          schema:
            $ref: '#/components/schemas/end'
          example: 1700341284
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorDataResponse'
              example:
                sensor_id: 123
                measurement: air_temperature
                data:
                  timestamp:
                    - 1700168549
                    - 1700254926
                    - 1700341284
                  value:
                    - 22
                    - 23.5
                    - 24
        '401':
          description: Invalid or missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '404':
          description: The advice was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
components:
  schemas:
    username:
      type: string
      description: Client username
    password:
      type: string
      description: Client password
    station_id:
      type: integer
      description: A station unique identity number
    sensor_id:
      type: integer
      description: A sensor unique identity number
    start:
      type: integer
      format: timestamp
      description: The date time from which data will be retrieved in timestamp format. If missing is set to datetime now
    end:
      type: integer
      format: timestamp
      description: The date time to which data will be retrieved in timestamp format. If missing is set to datetime now minus 3 days
    AuthenticationRequest:
      type: object
      properties:
        username:
          $ref: '#/components/schemas/username'
        password:
          $ref: '#/components/schemas/password'
      required:
        - username
        - password
      example:
        username: user1
        password: User1678!
    AuthenticationResponse:
      type: object
      properties:
        access_token:
          type: string
          format: Base64url
          description: A jwt session access token
    StationsResponse:
      type: object
      properties:
        station_id:
          $ref: '#/components/schemas/station_id'
        date_created:
          type: string
          format: YYYY-MM-DD
          description: The date that the station started to take records
        longitude:
          type: number
          format: float
          description: The longitude of the station installtion point
        latitude:
          type: number
          format: float
          description: The latitude of the station installtion point
        elevation:
          type: number
          format: float
          description: The elevation of the station installtion point
    StationSensorsResponse:
      type: object
      properties:
        sensor_id:
          $ref: '#/components/schemas/sensor_id'
        measurement:
          type: string
          description: Sensor measuring parameter
        unit:
          type: string
          description: The unit of the sensor measurements
        gauge_height:
          type: number
          format: float
          description: The height that the sensor is installed compared with station elevation
    StationDataResponse:
      type: object
      properties:
        station_id:
          $ref: '#/components/schemas/station_id'
        station_data:
          type: object
          description: a json with the station monitored parameters
          properties:
            parameter_name:
              type: object
              description: a parameter monitored by the station
              properties:
                data:
                  type: object
                  properties:
                    timestamp:
                      type: integer
                      format: timestamp
                      description: An array of of date-times in timestamp format
                    value:
                      type: number
                      format: float
                      description: An array of sensor meausrement
    SensorDataResponse:
      type: object
      properties:
        sensor_id:
          $ref: '#/components/schemas/sensor_id'
        measurement:
          type: string
          description: Sensor measuring parameter
        data:
          type: object
          properties:
            timestamp:
              type: integer
              format: timestamp
              description: An array of of date-times in timestamp format
            value:
              type: number
              format: float
              description: An array of sensor meausrement
    DetailedError:
      type: object
      description: This defines the structure of an error payload when one is present. Actual messages and additional error information content may change from one implementation to another
      properties:
        message:
          type: string
          description: error description
        status:
          type: string
          format: number
          description: http error code
        errors:
          type: array
          items:
            type: string
          description: Additional detailed information
      required:
        - message
      example:
        message: this is a sample error message
        errors:
          - this is an example of additional error information
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
